### ISSUE TITLE
advice_for_writers.md

### ISSUE THREAD

**Issue by zRich** [lfapac-open-source-evangelist/fabric-docs-i18n#1]
translate docs/locale/en_US/source/advice_for_writers.md -> docs/locale/zh_CN/source/advice_for_writers.md

**Comment by zRich** [comment]
total files to be translated. 

docs/locale/en_US/source/advice_for_writers.md
docs/locale/en_US/source/chaincode_lifecycle.md
docs/locale/en_US/source/CONTRIBUTING.rst
docs/locale/en_US/source/couchdb_tutorial.rst
docs/locale/en_US/source/deploy_chaincode.md
docs/locale/en_US/source/discovery-cli.md
docs/locale/en_US/source/discovery-overview.rst
docs/locale/en_US/source/docs_guide.md
docs/locale/en_US/source/fabric_model.rst
docs/locale/en_US/source/gateway.md
docs/locale/en_US/source/getting_started_run_fabric.rst
docs/locale/en_US/source/idemix.rst
docs/locale/en_US/source/install.md
docs/locale/en_US/source/international_languages.md
docs/locale/en_US/source/peer-chaincode-devmode.md
docs/locale/en_US/source/private_data_tutorial.rst
docs/locale/en_US/source/questions.rst
docs/locale/en_US/source/sdk_chaincode.md
docs/locale/en_US/source/style_guide.md
docs/locale/en_US/source/test_network.md
docs/locale/en_US/source/whatsnew.rst
docs/locale/en_US/source/write_first_app.rst
docs/locale/en_US/source/_static/images/discord_button.png
docs/locale/en_US/source/_templates/layout.html
docs/locale/en_US/source/commands/ledgerutil.md
docs/locale/en_US/source/deploypeer/peerchecklist.md
docs/locale/en_US/source/ledger/ledger.md
docs/locale/en_US/source/membership/membership.md
docs/locale/en_US/source/network/network.md
docs/locale/en_US/source/orderer/ordering_service.md
docs/locale/en_US/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md
docs/locale/en_US/source/secured_asset_transfer/transfer_assets_1.png
docs/locale/en_US/source/secured_asset_transfer/transfer_assets_2.png
docs/locale/en_US/source/secured_asset_transfer/transfer_assets_3.png
docs/locale/en_US/source/secured_asset_transfer/transfer_assets_images.pptx
docs/locale/en_US/wrappers/ledgerutil_postscript.md
docs/locale/en_US/wrappers/ledgerutil_preamble.md

**Comment by terizhao** [comment]
In reviewing on 9th, July
